site_name: Deivid Carvalho
site_url: https://example.com/
theme: material

nav:
    - About-me: about/whoAmI.md

    #- WebService: fazer.md

    #- DataBase: fazer.md

    #- IA: fazer.md

    - Experiencies:
      - WebService: experiencies/webService.md
      - DataBase: experiencies/database.md
      - Artificial Intelligence: experiencies/IA.md
      
      